version: '2'
services:
    web:
        image: michaloo/wordpress
        env_file: .env
        volumes:
            - web_data:/var/www/html
            - .:/project
            # enable line below to start theme development
            # - ./example-theme-src:/var/www/html/wp-content/themes/example-theme
            # enable line below to start plugin development
            # - ./example-plugin-src:/var/www/html/wp-content/plugins/example-plugin
        ports:
            - "80:80"
        links:
            - mysql
    mysql:
        image: mariadb
        env_file: .env
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
    mysql_data: {}
    web_data: {}
