version: '2'
services:
    web:
        image: wordpress
        env_file: .env
        volumes:
            - ./wordpress_data:/var/www/html/
            # uncomment line below to start theme development
            # - ./example-theme-src:/var/www/html/wp-content/themes/example-theme
            # uncomment line below to start plugin development
            # - ./example-plugin-src:/var/www/html/wp-content/plugins/example-plugin
        ports:
            - "80:80"
        links:
            - mysql
    mysql:
        image: mariadb
        env_file: .env
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
    mysql_data: {}
